# Generated by Django 5.0.6 on 2024-05-14 02:42

import mapbox_location_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'style': 'mapbox://styles/mapbox/streets-v11'})),
            ],
        ),
    ]
