# Generated by Django 5.0.6 on 2024-05-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customerfeedback_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
